<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-11T06:50:15Z" name="Facebook" finished-at="2021-05-11T06:50:26Z" duration-ms="11960">
    <groups>
    </groups>
    <test started-at="2021-05-11T06:50:15Z" name="Test" finished-at="2021-05-11T06:50:26Z" duration-ms="11960">
      <class name="pom.FlipkartTests">
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.FlipkartTests@37ceb1df]" started-at="2021-05-11T06:50:15Z" name="before" finished-at="2021-05-11T06:50:19Z" duration-ms="4841" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2d5f7182]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="flipkartValidInputTest()[pri:0, instance:pom.FlipkartTests@37ceb1df]" started-at="2021-05-11T06:50:19Z" name="flipkartValidInputTest" finished-at="2021-05-11T06:50:25Z" duration-ms="5894" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [Showing 1 – 24 of 689 results for "mobiles"] but found [Showing 1 – 24 of 704 results for "mobiles"]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.AssertionError: expected [Showing 1 – 24 of 689 results for "mobiles"] but found [Showing 1 – 24 of 704 results for "mobiles"]
at pom.FlipkartTests.flipkartValidInputTest(FlipkartTests.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.AssertionError: expected [Showing 1 – 24 of 689 results for "mobiles"] but found [Showing 1 – 24 of 704 results for "mobiles"]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pom.FlipkartTests.flipkartValidInputTest(FlipkartTests.java:53)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flipkartValidInputTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.FlipkartTests@37ceb1df]" started-at="2021-05-11T06:50:26Z" name="quit" finished-at="2021-05-11T06:50:26Z" duration-ms="744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- pom.FlipkartTests -->
    </test> <!-- Test -->
  </suite> <!-- Facebook -->
</testng-results>
